<a href="https://colab.research.google.com/github/jrangelg/Artificial-intelligence/blob/main/Muestreo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
install.packages('survey')

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘minqa’, ‘numDeriv’, ‘mitools’, ‘RcppArmadillo’

In [3]:
# Tamano de muestra
e<-c(rep(0.1,3),rep(0.2,3),rep(0.3,3),rep(0.4,3),rep(0.5,3))
a<-c(rep(c(0.05,0.01,0.005),5))
a
matriz_base<-data.frame(e,a,n=rep(0,15))
matriz_base
for(i in 1:15){
  matriz_base[i,3]<-(qnorm(matriz_base[i,2]/2)**2)/(matriz_base[i,1]**2)
}
matriz_base
#MAS
library ( survey )
data ( iris )
iris$fpc_mas <- 500
N<-iris$fpc_mas[1]
n<-length(iris$Sepal.Length)
w<-N/n
pi<-n/N
w
diseno_mas <- svydesign( id = ~1 , weights = NULL ,#strata =
                         , fpc = ~fpc_mas ,
                           data = iris )
View(iris)
mean<-svymean(~Sepal.Length,diseno_mas)
mean
confint(mean)
sd(iris$Sepal.Length)/sqrt(150)
t.test(iris$Sepal.Length)
#Estratificado
iris$fpc_est<-200
diseno_est <- svydesign( id = ~1 ,strata = ~Species, weights = NULL , fpc = ~fpc_est ,
                         data = iris )
table(iris$Species)
mean<-svymean(~Sepal.Length,diseno_est)
mean
confint(mean)

View(Titanic)
df_titanic <-as.data.frame(Titanic)
diseno_cong <- svydesign(
id = ~Class ,
weights = ~Freq ,
data = df_titanic
)
prop_survived <- svymean(~ Survived , diseno_cong)
print(prop_survived)
prop.test(sum(df_titanic$Survived == 'Yes'),length(df_titanic$Survived == 'Yes'))
confint(prop_survived)
sd(prop_survived)/3
prop_survived

# Parámetros iniciales de ejemplo
# N_h: Tamaño de la población en cada estrato
# S_h: Desviación estándar de la variable en cada estrato
# c_h: Costo por unidad muestreada en cada estrato
N_h <- c(1000, 2500, 1500)
S_h <- c(12, 8, 15)
c_h <- c(4, 9, 16)
n_total <- 200 # Tamaño de muestra total deseado

N <- sum(N_h)

# 1. Afijación Proporcional al Tamaño
# n_h = n * (N_h / N)
n_prop <- round(n_total * (N_h / N))
n_prop
# 2. Afijación de Neyman (considera tamaño y variabilidad S_h)
# n_h = n * (N_h * S_h) / sum(N_h * S_h)
num_neyman <- N_h * S_h
n_neyman <- round(n_total * (num_neyman / sum(num_neyman)))

# 3. Afijación Óptima (considerando costos c_h y variabilidad S_h)
# n_h = n * (N_h * S_h / sqrt(c_h)) / sum(N_h * S_h / sqrt(c_h))
num_optimo <- (N_h * S_h) / sqrt(c_h)
n_optimo <- round(n_total * (num_optimo / sum(num_optimo)))

# Consolidar resultados en una tabla
resultados <- data.frame(
  Estrato = 1:length(N_h),
  N_h = N_h,
  S_h = S_h,
  Costo_h = c_h,
  Proporcional = n_prop,
  Neyman = n_neyman,
  Optimo_Costos = n_optimo
)

print(resultados)

library(survey)

# Cargar el conjunto de datos estratificado por defecto del paquete survey
data(api)
# apistrat contiene una muestra estratificada de escuelas (por tipo: E, M, H)
# Variables clave: stype (estrato), pw (pesos de muestreo), fpc (corrección por población finita), api00 (variable de interés)

# 1. Definir el diseño de muestreo estratificado
# id=~1: Muestreo aleatorio simple dentro de estratos
# strata=~stype: Variable de estratificación
# weights=~pw: Pesos muestrales (inversos de probabilidad de inclusión)
# fpc=~fpc: Corrección para población finita (tamaño poblacional por estrato)
dstrat <- svydesign(id = ~1, strata = ~stype, weights = ~pw, data = apistrat, fpc = ~fpc)
View(apistrat)
sum(apistrat$pw)
length(apistrat$pw)
# --- EJEMPLO 1: Estimación de la Media Poblacional ---
# Estimar la media del puntaje académico en el año 2000 (api00)
media_api00 <- svymean(~api00, dstrat)
print("--- Estimación de la Media ---")
print(media_api00)
# Intervalo de confianza al 95% para la media
confint(media_api00)
apistrat$fpcmas<-1000
dsmas <- svydesign(id = ~1, data = apistrat, fpc = ~fpcmas)
mediamas<-svymean(~api00,dsmas)
confint(mediamas)
# --- EJEMPLO 2: Estimación del Total Poblacional ---
# Estimar el total de la matrícula estudiantil (enroll) o del puntaje acumulado
total_enroll <- svytotal(~enroll, dstrat)
print("--- Estimación del Total ---")
print(total_enroll)
confint(total_enroll)


# --- EJEMPLO 3: Estimación por Dominios (Subpoblaciones) ---
# Estimar la media y el total de api00 desglosado por un dominio (ej. si la escuela recibe premios 'awards')
media_por_dominio <- svyby(~api00, ~awards, dstrat, svymean)
total_por_dominio <- svyby(~api00, ~awards, dstrat, svytotal)

print("--- Media por Dominio (awards) ---")
print(media_por_dominio)

print("--- Total por Dominio (awards) ---")
print(total_por_dominio)

 [1] 0.050 0.010 0.005 0.050 0.010 0.005 0.050 0.010 0.005 0.050 0.010 0.005
[13] 0.050 0.010 0.005

   e   a     n
1  0.1 0.050 0
2  0.1 0.010 0
3  0.1 0.005 0
4  0.2 0.050 0
5  0.2 0.010 0
6  0.2 0.005 0
7  0.3 0.050 0
8  0.3 0.010 0
9  0.3 0.005 0
10 0.4 0.050 0
11 0.4 0.010 0
12 0.4 0.005 0
13 0.5 0.050 0
14 0.5 0.010 0
15 0.5 0.005 0

   e   a     n
1  0.1 0.050 384.14588
2  0.1 0.010 663.48966
3  0.1 0.005 787.94386
4  0.2 0.050  96.03647
5  0.2 0.010 165.87242
6  0.2 0.005 196.98596
7  0.3 0.050  42.68288
8  0.3 0.010  73.72107
9  0.3 0.005  87.54932
10 0.4 0.050  24.00912
11 0.4 0.010  41.46810
12 0.4 0.005  49.24649
13 0.5 0.050  15.36584
14 0.5 0.010  26.53959
15 0.5 0.005  31.51775

Loading required package: grid

Loading required package: Matrix

Loading required package: survival


Attaching package: ‘survey’


The following object is masked from ‘package:graphics’:

    dotchart

[1] 3.333333

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species   fpc_mas
1   5.1          3.5         1.4          0.2         setosa    500
2   4.9          3.0         1.4          0.2         setosa    500
3   4.7          3.2         1.3          0.2         setosa    500
4   4.6          3.1         1.5          0.2         setosa    500
5   5.0          3.6         1.4          0.2         setosa    500
6   5.4          3.9         1.7          0.4         setosa    500
7   4.6          3.4         1.4          0.3         setosa    500
8   5.0          3.4         1.5          0.2         setosa    500
9   4.4          2.9         1.4          0.2         setosa    500
10  4.9          3.1         1.5          0.1         setosa    500
11  5.4          3.7         1.5          0.2         setosa    500
12  4.8          3.4         1.6          0.2         setosa    500
13  4.8          3.0         1.4          0.1         setosa    500
14  4.3          3.0         1.1          0.1         setosa    500
15  5.8          4.0         1.2          0.2         setosa    500
16  5.7          4.4         1.5          0.4         setosa    500
17  5.4          3.9         1.3          0.4         setosa    500
18  5.1          3.5         1.4          0.3         setosa    500
19  5.7          3.8         1.7          0.3         setosa    500
20  5.1          3.8         1.5          0.3         setosa    500
21  5.4          3.4         1.7          0.2         setosa    500
22  5.1          3.7         1.5          0.4         setosa    500
23  4.6          3.6         1.0          0.2         setosa    500
24  5.1          3.3         1.7          0.5         setosa    500
25  4.8          3.4         1.9          0.2         setosa    500
26  5.0          3.0         1.6          0.2         setosa    500
27  5.0          3.4         1.6          0.4         setosa    500
28  5.2          3.5         1.5          0.2         setosa    500
29  5.2          3.4         1.4          0.2         setosa    500
30  4.7          3.2         1.6          0.2         setosa    500
⋮   ⋮            ⋮           ⋮            ⋮           ⋮         ⋮
121 6.9          3.2         5.7          2.3         virginica 500
122 5.6          2.8         4.9          2.0         virginica 500
123 7.7          2.8         6.7          2.0         virginica 500
124 6.3          2.7         4.9          1.8         virginica 500
125 6.7          3.3         5.7          2.1         virginica 500
126 7.2          3.2         6.0          1.8         virginica 500
127 6.2          2.8         4.8          1.8         virginica 500
128 6.1          3.0         4.9          1.8         virginica 500
129 6.4          2.8         5.6          2.1         virginica 500
130 7.2          3.0         5.8          1.6         virginica 500
131 7.4          2.8         6.1          1.9         virginica 500
132 7.9          3.8         6.4          2.0         virginica 500
133 6.4          2.8         5.6          2.2         virginica 500
134 6.3          2.8         5.1          1.5         virginica 500
135 6.1          2.6         5.6          1.4         virginica 500
136 7.7          3.0         6.1          2.3         virginica 500
137 6.3          3.4         5.6          2.4         virginica 500
138 6.4          3.1         5.5          1.8         virginica 500
139 6.0          3.0         4.8          1.8         virginica 500
140 6.9          3.1         5.4          2.1         virginica 500
141 6.7          3.1         5.6          2.4         virginica 500
142 6.9          3.1         5.1          2.3         virginica 500
143 5.8          2.7         5.1          1.9         virginica 500
144 6.8          3.2         5.9          2.3         virginica 500
145 6.7          3.3         5.7          2.5         virginica 500
146 6.7          3.0         5.2          2.3         virginica 500
147 6.3          2.5         5.0          1.9         virginica 500
148 6.5          3.0         5.2          2.0         virginica 500
149 6.2          3.4         5.4          2.3         virginica 500
150 5.9          3.0         5.1          1.8         virginica 500

               mean     SE
Sepal.Length 5.8433 0.0566

             2.5 %    97.5 %
Sepal.Length 5.732463 5.954204

[1] 0.06761132

	One Sample t-test

data:  iris$Sepal.Length
t = 86.425, df = 149, p-value < 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 5.709732 5.976934
sample estimates:
mean of x
 5.843333

    setosa versicolor  virginica
        50         50         50

               mean     SE
Sepal.Length 5.8433 0.0364

             2.5 %    97.5 %
Sepal.Length 5.771988 5.914678

, , Age = Child, Survived = No

      Sex
Class  Male Female
  1st     0      0
  2nd     0      0
  3rd    35     17
  Crew    0      0

, , Age = Adult, Survived = No

      Sex
Class  Male Female
  1st   118      4
  2nd   154     13
  3rd   387     89
  Crew  670      3

, , Age = Child, Survived = Yes

      Sex
Class  Male Female
  1st     5      1
  2nd    11     13
  3rd    13     14
  Crew    0      0

, , Age = Adult, Survived = Yes

      Sex
Class  Male Female
  1st    57    140
  2nd    14     80
  3rd    75     76
  Crew  192     20

               mean     SE
SurvivedNo  0.67697 0.0709
SurvivedYes 0.32303 0.0709

	1-sample proportions test without continuity correction

data:  sum(df_titanic$Survived == "Yes") out of length(df_titanic$Survived == "Yes"), null probability 0.5
X-squared = 0, df = 1, p-value = 1
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
 0.3363088 0.6636912
sample estimates:
  p
0.5

            2.5 %     97.5 %
SurvivedNo  0.5380767 0.8158534
SurvivedYes 0.1841466 0.4619233

[1] 0.08342211

               mean     SE
SurvivedNo  0.67697 0.0709
SurvivedYes 0.32303 0.0709

[1]  40 100  60

  Estrato  N_h S_h Costo_h Proporcional Neyman Optimo_Costos
1       1 1000  12       4           40     44            66
2       2 2500   8       9          100     73            73
3       3 1500  15      16           60     83            62

    cds            stype name
1   19647336097927 E     Open Magnet: Ce
2   19647336016018 E     Belvedere Eleme
3   19648816021505 E     Altadena Elemen
4   19647336019285 E     Soto Street Ele
5   56739406115430 E     Walnut Canyon E
6   56726036084917 E     Atherwood Eleme
7   56726036055800 E     Township Elemen
8   15633216109078 E     Thorner (Dr. Ju
9   37683956098487 E     Nicoloff (Georg
10  37680236038020 E     Valle Lindo Ele
11  36678506059448 M     Frisbie Middle
12  33752426111447 M     Rivera (Tomas)
13  10621661035831 H     Roosevelt High
14  01612596057020 M     Frick Middle
15  33752423330552 H     Rancho Verde Hi
16  19647336016620 E     Corona Avenue E
17  30665226028732 E     Rosita Elementa
18  33671736059109 M     Cree (Raymond)
19  30736506071179 M     Rancho San Joaq
20  10623316007009 E     Orange Center E
21  14632556008726 E     Pine Street Ele
22  43696746101752 M     Buchser Middle
23  43696256048110 E     Frost (Earl) El
24  54753255430210 H     Farmersville Hi
25  36677103630555 H     Fontana Miller
26  01612596001754 E     Crocker Highlan
27  19644361938372 H     South Hills Hig
28  49738824935482 H     Rancho Cotate H
29  19647336017719 E     Kentwood Elemen
30  37681976067003 M     La Presa Middle
⋮   ⋮              ⋮     ⋮
171 07617966057236 M     Pinole Junior H
172 14632486008692 E     Big Pine Elemen
173 37684526059810 M     Washington Midd
174 34674393437555 H     Sacramento High
175 19647336068431 M     El Sereno Middl
176 38684783830254 H     Burton (Phillip
177 22655322235356 H     Mariposa County
178 19734371931963 H     Compton High
179 23655406025084 E     Anderson Valley
180 23656152335024 H     Ukiah High
181 33671736112692 M     Workman (James)
182 19647331933381 H     Garfield (James
183 30736356101059 E     Del Lago Elemen
184 37682966038988 M     Meadowbrook Mid
185 01612596001994 E     Laurel Elementa
186 30665636028948 E     El Cerrito Elem
187 56726036055776 E     Santa Susana El
188 43696906049217 E     Fairwood Elemen
189 39685696105738 E     Pacific (K-8)
190 56726035630322 H     Santa Susana Hi
191 33751766032056 E     Machado Element
192 15634121531672 H     Delano High
193 07617880735407 H     Pittsburg Senio
194 19650526022933 E     Emperor Element
195 01612426001572 E     Alvarado Elemen
196 19647336018568 E     One Hundred Twe
197 33670333331600 H     Corona Senior H
198 04755076003164 M     Sycamore Middle
199 56724626055016 E     Larsen (Ansgar)
200 31669513134657 H     Lincoln High (C
    sname                                    snum dname
1   Open Magnet: Center for Individual (Char 2077 Los Angeles Unified
2   Belvedere Elementary                     1622 Los Angeles Unified
3   Altadena Elementary                      2236 Pasadena Unified
4   Soto Street Elementary                   1921 Los Angeles Unified
5   Walnut Canyon Elementary                 6140 Moorpark Unified
6   Atherwood Elementary                     6077 Simi Valley Unified
7   Township Elementary                      6071 Simi Valley Unified
8   Thorner (Dr. Juliet) Elementary           904 Bakersfield City Elem
9   Nicoloff (George) Elementary             4637 South Bay Union Elem
10  Valle Lindo Elementary                   4311 Chula Vista Elementary
11  Frisbie Middle                           4105 Rialto Unified
12  Rivera (Tomas) Middle                    3607 Val Verde Unified
13  Roosevelt High                            627 Fresno Unified
14  Frick Middle                              215 Oakland Unified
15  Rancho Verde High                        3599 Val Verde Unified
16  Corona Avenue Elementary                 1678 Los Angeles Unified
17  Rosita Elementary                        3015 Garden Grove Unified
18  Cree (Raymond) Middle                    3491 Palm Springs Unified
19  Rancho San Joaquin Middle                3237 Irvine Unified
20  Orange Center Elementary                  725 Orange Center Elementary
21  Pine Street Elementary                    861 Bishop Union Elementary
22  Buchser Middle                           5410 Santa Clara Unified
23  Frost (Earl) Elementary                  5319 Oak Grove Elementary
24  Farmersville High                        5947 Farmersville Unified
25  Fontana Miller (A.B.) High               3999 Fontana Unified
26  Crocker Highlands Elementary              169 Oakland Unified
27  South Hills High                         1247 Covina-Valley Unified
28  Rancho Cotate High                       5706 Cotati-Rohnert Park Unif
29  Kentwood Elementary                      1777 Los Angeles Unified
30  La Presa Middle                          4398 La Mesa-Spring Valley
⋮   ⋮                                        ⋮    ⋮
171 Pinole Junior High                        498 West Contra Costa Unified
172 Big Pine Elementary                       859 Big Pine Unified
173 Washington Middle                        4649 Vista Unified
174 Sacramento High                          3732 Sacramento City Unified
175 El Sereno Middle                         2072 Los Angeles Unified
176 Burton (Phillip & Sala) Academic High    4686 San Francisco Unified
177 Mariposa County High                     2625 Mariposa County Unified
178 Compton High                             2426 Compton Unified
179 Anderson Valley Elementary               2631 Anderson Valley Unified
180 Ukiah High                               2641 Ukiah Unified
181 Workman (James) Middle                   3497 Palm Springs Unified
182 Garfield (James A.) Senior High          1563 Los Angeles Unified
183 Del Lago Elementary                      3203 Saddleback Valley Unif
184 Meadowbrook Middle                       4426 Poway Unified
185 Laurel Elementary                         189 Oakland Unified
186 El Cerrito Elementary                    3030 La Habra City Elementary
187 Santa Susana Elementary                  6068 Simi Valley Unified
188 Fairwood Elementary                      5421 Sunnyvale Elementary
189 Pacific (K-8)                            4801 Lincoln Unified
190 Santa Susana High                        6054 Simi Valley Unified
191 Machado Elementary                       3563 Lake Elsinore Unified
192 Delano High                               938 Delano Joint Union High
193 Pittsburg Senior High                     448 Pittsburg Unified
194 Emperor Elementary                       2338 Temple City Unified
195 Alvarado Elementary                       146 New Haven Unified
196 One Hundred Twelfth Street Elementary    1858 Los Angeles Unified
197 Corona Senior High                       3365 Corona-Norco Unified
198 Sycamore Middle                           336 Gridley Unified
199 Larsen (Ansgar) Elementary               5986 Hueneme Elementary
200 Lincoln High (Char)                      3324 Western Placer Unified
    dnum cname          cnum flag ⋯ some.col col.grad grad.sch avg.ed full emer
1   401  Los Angeles    18   NA   ⋯  0         0       0       3.32   100   0
2   401  Los Angeles    18   NA   ⋯  0         0       0       1.67    57  40
3   541  Los Angeles    18   NA   ⋯  0         0       0       2.34    81  26
4   401  Los Angeles    18   NA   ⋯  0         0       0       1.86    64  24
5   460  Ventura        55   NA   ⋯  0         0       0       3.17    90   7
6   689  Ventura        55   NA   ⋯  0         0       0       3.64    95   0
7   689  Ventura        55   NA   ⋯  0         0       0       3.55    96   0
8    41  Kern           14   NA   ⋯  0         0       0       3.10    93   8
9   702  San Diego      36   NA   ⋯  0         0       0       2.17    91  14
10  135  San Diego      36   NA   ⋯  0         0       0       2.82    96   0
11  590  San Bernardino 35   NA   ⋯  0         0       0       2.21    84  18
12  767  Riverside      32   NA   ⋯ 22        10       4       2.22    65  37
13  253  Fresno          9   NA   ⋯ 15        12       4       2.01    93  17
14  507  Alameda         1   NA   ⋯ 23        29       3       2.79    55  26
15  767  Riverside      32   NA   ⋯ 31        23       6       2.73    80  19
16  401  Los Angeles    18   NA   ⋯ 11         8       0       1.82    67  33
17  259  Orange         29   NA   ⋯ 18         9       0       2.27    97   3
18  531  Riverside      32   NA   ⋯ 32        16      11       2.75    89  13
19  316  Orange         29   NA   ⋯  0       100       0       4.00   100   7
20  515  Fresno          9   NA   ⋯ 13         2       2       1.61    90  14
21   69  Inyo           13   NA   ⋯ 27        28      11       3.11    97   0
22  656  Santa Clara    42   NA   ⋯ 31        28      10       3.06    89  11
23  501  Santa Clara    42   NA   ⋯ 46        26       5       3.13    78  22
24  233  Tulare         53   NA   ⋯ 14         3       1       1.68    81  19
25  238  San Bernardino 35   NA   ⋯ 18        13       1       2.19    81  15
26  507  Alameda         1   NA   ⋯ 22        27      43       4.03    95   0
27  162  Los Angeles    18   NA   ⋯ 30        30      16       3.31    77  17
28  160  Sonoma         48   NA   ⋯ 31        34       8       3.20    95   6
29  401  Los Angeles    18   NA   ⋯ 24        44      11       3.41    88   4
30  351  San Diego      36   NA   ⋯ 30        13       4       2.48   100   8
⋮   ⋮    ⋮              ⋮    ⋮    ⋱ ⋮        ⋮        ⋮        ⋮      ⋮    ⋮
171 796  Contra Costa    6   NA   ⋯ 28       34        8       3.13    80  13
172  64  Inyo           13   NA   ⋯ 38       32        5       3.16    92   0
173 780  San Diego      36   NA   ⋯ 28       18        6       2.53    96   1
174 620  Sacramento     33   NA   ⋯ 26       25        8       2.80    96   6
175 401  Los Angeles    18   NA   ⋯ 16       16        2       2.19    66  28
176 632  San Francisco  37   NA   ⋯ 20       29        4       2.68    84  14
177 423  Mariposa       21   NA   ⋯ 40       27       14       3.34    92   8
178 153  Los Angeles    18   NA   ⋯ 15       14        1       1.97    70  30
179  25  Mendocino      22   NA   ⋯ 13       13        7       2.10   100   0
180 760  Mendocino      22   NA   ⋯ 34       16       16       2.99    97   6
181 531  Riverside      32   NA   ⋯ 33       21        6       2.74    71  18
182 401  Los Angeles    18   NA   ⋯  8        5        1       1.62    83  17
183 621  Orange         29   NA   ⋯ 27       35        9       3.16    97   6
184 575  San Diego      36   NA   ⋯ 29       36       25       3.71   100   3
185 507  Alameda         1   NA   ⋯ 32       16        7       2.63    82   7
186 349  Orange         29   NA   ⋯ 21        3        2       1.98    91   9
187 689  Ventura        55   NA   ⋯  0        0        0       1.50    96   0
188 725  Santa Clara    42   NA   ⋯ 28       35        7       3.10    68  26
189 382  San Joaquin    38   NA   ⋯ 32       23       24       3.40    88  12
190 689  Ventura        55   NA   ⋯ 50        0       50       4.00    88   5
191 358  Riverside      32   NA   ⋯ 25       11        4       2.38    83  17
192 176  Kern           14   NA   ⋯ 14       14        1       1.96    68  28
193 554  Contra Costa    6   NA   ⋯ 20       31        2       2.67    65  34
194 738  Los Angeles    18   NA   ⋯ 20       27       23       3.34    67  30
195 484  Alameda         1   NA   ⋯ 33       33       10       3.23   100   0
196 401  Los Angeles    18   NA   ⋯ 10       33        0       2.67    42  39
197 158  Riverside      32   NA   ⋯ 29       25        9       2.86    95   4
198 279  Butte           3   NA   ⋯ 20       16        4       2.40    78  13
199 308  Ventura        55   NA   ⋯  0        0        0       1.61    95   5
200 802  Placer         30   NA   ⋯ 34       25        5       2.91    97   3
    enroll api.stu pw    fpc
1    276    241    44.21 4421
2    841    631    44.21 4421
3    441    415    44.21 4421
4    298    288    44.21 4421
5    354    319    44.21 4421
6    330    315    44.21 4421
7    385    363    44.21 4421
8    583    510    44.21 4421
9    763    652    44.21 4421
10   381    322    44.21 4421
11  1293   1035    20.36 1018
12  1043    815    20.36 1018
13  2165   1850    15.10  755
14   739    658    20.36 1018
15  1894   1451    15.10  755
16  1112    931    44.21 4421
17   515    447    44.21 4421
18  1116    966    20.36 1018
19   739    585    20.36 1018
20   262    192    44.21 4421
21   528    479    44.21 4421
22   912    796    20.36 1018
23   278    266    44.21 4421
24   357    302    15.10  755
25  2552   2238    15.10  755
26   266    241    44.21 4421
27  1105    851    15.10  755
28  1586   1349    15.10  755
29   256    222    44.21 4421
30  1173    923    20.36 1018
⋮   ⋮      ⋮       ⋮     ⋮
171  933    756    20.36 1018
172  153    123    44.21 4421
173 1524   1254    20.36 1018
174 1389   1137    15.10  755
175 2171   1995    20.36 1018
176 1313   1111    15.10  755
177  542    430    15.10  755
178 1684   1208    15.10  755
179  213    175    44.21 4421
180 1520   1306    15.10  755
181 1012   1082    20.36 1018
182 3156   2900    15.10  755
183  410    372    44.21 4421
184 1358   1182    20.36 1018
185  364    347    44.21 4421
186  169    142    44.21 4421
187  368    332    44.21 4421
188  190    168    44.21 4421
189  368    314    44.21 4421
190  763    691    15.10  755
191  601    457    44.21 4421
192 2237   1248    15.10  755
193 1602   1178    15.10  755
194  420    352    44.21 4421
195  613    534    44.21 4421
196  446    351    44.21 4421
197 1754   1516    15.10  755
198  423    369    20.36 1018
199  482    446    44.21 4421
200  599    517    15.10  755

[1] 6194

[1] 200

[1] "--- Estimación de la Media ---"
        mean     SE
api00 662.29 9.4089

      2.5 %    97.5 %
api00 643.8462 680.7285

      2.5 %    97.5 %
api00 637.8245 667.8155

[1] "--- Estimación del Total ---"
         total     SE
enroll 3687178 114642

       2.5 %   97.5 %
enroll 3462484 3911871

[1] "--- Media por Dominio (awards) ---"
    awards    api00       se
No      No 633.7349 15.33477
Yes    Yes 678.4224 11.85663
[1] "--- Total por Dominio (awards) ---"
    awards   api00       se
No      No 1417304 142752.7
Yes    Yes 2684904 152042.2